import type { NoteHitRow, NoteRow, NotebookRow, TagRow } from "./rows.js";
import type {
  NewNoteInput,
  NewNotebookInput,
  NewTagInput,
  NoteFilter,
  NotePatch,
  Page,
} from "./types.js";

/**
 * The thin wire-level port the SupabaseNotesAdapter talks to. The real
 * binding (in M06 / M12) wraps @supabase/supabase-js + Database types
 * generated by `supabase gen types`; tests pass a fake. Keeping the port
 * shape PostgREST-friendly (snake_case rows, owner_id stamping on the
 * server side via auth.uid()) means the binding is a thin translation.
 */
export interface NotesHttp {
  // Notes
  selectNotes(filter: NoteFilter, page: Page): Promise<{ items: NoteRow[]; total: number }>;
  selectNote(id: string): Promise<NoteRow | null>;
  insertNote(input: NewNoteInput): Promise<NoteRow>;
  patchNote(id: string, patch: NotePatch): Promise<NoteRow>;
  setNoteTrashed(id: string, isTrashed: boolean): Promise<void>;

  // Notebooks
  selectNotebooks(): Promise<NotebookRow[]>;
  insertNotebook(input: NewNotebookInput): Promise<NotebookRow>;
  patchNotebook(id: string, patch: { name?: string; color?: string }): Promise<NotebookRow>;
  deleteNotebook(id: string, moveNotesTo: string | null): Promise<void>;

  // Tags
  selectTags(): Promise<TagRow[]>;
  insertTag(input: NewTagInput): Promise<TagRow>;
  mergeTag(from: string, into: string): Promise<void>;

  // Search
  searchNotes(q: string, filter: NoteFilter): Promise<NoteHitRow[]>;
}

export class NotesNotFoundError extends Error {
  readonly code = "ERR_NOT_FOUND" as const;
  constructor(public readonly id: string) {
    super(`Note ${id} not found`);
  }
}
